name: "ci-driven-scanner"
description: "Runs an Enterprise scan against a target site"
author: "PortSwigger Cloud"

inputs:
  enterprise-server-url:
    description: "The URL of your Enterprise server."
    required: false
  enterprise-api-key:
    description: "The API key that you copied when you created an API user."
    required: false
  start-url:
    description: "The URL of the website you want Burp Scanner to scan."
    required: false
  correlation-id:
    description: "You only need to input a correlation ID if you want to view the scan results on the Burp Suite Enterprise Edition web interface. You can use a text string up to 64 characters long."
    required: false
  reports-directory:
    description: "The directory to output reports to."
    required: false
    default: burp_reports
  config-file-path:
    description: "The file path of your burp config file, this path must be an absolute path."
    default: burp_config.yml
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    BURP_ENTERPRISE_SERVER_URL: ${{ inputs.enterprise-server-url }}
    BURP_ENTERPRISE_API_KEY: ${{ inputs.enterprise-api-key }}
    BURP_START_URL: ${{ inputs.start-url }}
    BURP_CORRELATION_ID: ${{ inputs.correlation-id }}
    BURP_REPORTS_DIRECTORY: ${{ inputs.reports-directory }}
    BURP_CONFIG_FILE_PATH: ${{ inputs.config-file-path }}
branding:
  icon: "shield"
  color: "blue"
